import Head from "next/head";

// Components
import Navbar from "@/common/components/Navbar";
import Hero from "@/common/components/Hero";
import Footer from "@/common/components/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Budget Buddy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
      </Head>
      <Navbar />
      <Hero />
      <Footer />
    </>
  )
}
